<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="home2.css">
  <title>STATION</title>
</head>
<body>
  <header>
      <nav>
          <div class="container">
              <h3 class="logo">MENU</h3>
              <div class="hamburger">
              <div class="bar"></div>
          </div>
          </div>
      </nav>
      <h1 class="big-title">PHOTOGRAPHY STATION</h1>

      <img src="Layer 3.jpg" class="langit" alt="">
      <img src="Layer2.png" class="halaman" alt="">
      <img src="Layer 1.png" class="orang" alt="">

     
  </header>
  <section>
      <div class="container">
          <div class="content">
          <h3 class="title">
              ABOUT
              <div class="border"></div>
          </h3>
          <p class="text">PHOTOGRAPHY STATION adalah web yang dimana menjadi tempat wadah saya disaat saya suatu hari nanti traveling, 
              Yang mana akan menjadi sebuah wadah saya menaruh hasil foto atau kenagan di setiap perjalanan saya, dan agar bisa di gunakan atau di 
              nikmati oleh orang lain</p>
          </div>
          <div class="imgcontainer">
              <img src="background.jpg" alt="">
          </div>
      </div>
  </section>
  
</body>
</html>